AUTOINSTALL="{{ plexupdate_autoinstall }}"
AUTOUPDATE="{{ plexupdate_autoupdate }}"
PUBLIC="{{ plexupdate_public }}"
AUTODELETE="yes"
PLEXSERVER="127.0.0.1"
PLEXPORT="32400"
NOTIFY="{{ plexupdate_notify }}"