---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: Debian9
    image: lansible/debian:9

  - name: Ubuntu1604
    image: lansible/ubuntu:16.04

provisioner:
  name: ansible
  options:
    v: true
  env:
    ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
  lint:
    name: ansible-lint

scenario:
  name: python3

verifier:
  name: goss
  enabled: false
