---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: Centos6
    image: centos:6
    ulimits:
      - memlock:60397977:60397977

  - name: Ubuntu1404
    image: wilmardo/docker-ubuntu-ansible:14.04

provisioner:
  name: ansible
  options:
    v: true
  lint:
    name: ansible-lint

scenario:
  name: legacy

verifier:
  name: goss
  enabled: false
